// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ReactJSAndASP.Models;
using System;
using System.Collections.Generic;

#nullable disable

namespace ReactJSAndASP.Models
{
    public partial class Booking
    {
        public Booking()
        {
            BookingInPaymentMap = new HashSet<BookingInPaymentMap>();
        }

		public Booking(Guid id, Guid fastFoodId, DateTime bookingTime, Guid accountClientId)
		{
			Id = id;
			FastFoodId = fastFoodId;
			BookingTime = bookingTime;
			AccountClientId = accountClientId;
		}

		public Guid Id { get; set; }
        public Guid FastFoodId { get; set; }
        public DateTime BookingTime { get; set; }
        public Guid AccountClientId { get; set; }
		public int NumberTable { get; set; }
		public virtual AccountClient AccountClient { get; set; }
        public virtual FastFood FastFood { get; set; }
        public virtual ICollection<BookingInPaymentMap> BookingInPaymentMap { get; set; }
    }
}