// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ReactJSAndASP.Models
{
    public partial class PaymentOfBooking
    {
        public PaymentOfBooking()
        {
            BookingInPaymentMap = new HashSet<BookingInPaymentMap>();
        }

        public Guid Id { get; set; }
        public Guid? AccountClientId { get; set; }
        public decimal? TotalOrders { get; set; }
        public bool? PaidUp { get; set; }

        public virtual AccountClient AccountClient { get; set; }
        public virtual ICollection<BookingInPaymentMap> BookingInPaymentMap { get; set; }
    }
}